season1 = ["HelpWanted", "ReefBlower", "Tea at the Treedome", "Bubblestand", "Ripped Pants", "Jellyfishing", "Plankton!", "Naughty Nautical Neighbors", "Boating School", "Pizza Delivery", "Home Sweet Pineapple", "Mermaid Man and Barnacle Boy", "Pickles", "Hall Monitor", "Jellyfish Jam", "Sandy's Rocket", "Squeaky Boots", "Nature Pants", "Opoosite Day", "Culture Shock", "F.U.N", "MuscleBob BuffPants", "Squidward the Unfriendly Ghost", "The Chaperone", "Employee of the Mpnth", "Scaredy Pants", "I Was a Teenage Gary", "SB-129", "Karate Choppers", "Sleepy Time", "Suds", "Valentine's Day", "The Paper", "Arrgh!", "Rock Bottom", "Texas", "Walking Small", "Fools In April", "Neptune's Spatula", "Hooky", "Memaid Man and Barnacle Boy II"]
const season2 = [
  "Your Shoe's Untied", "Squid's Day Off","Something Smells","Bossy Boots","Big Pink Loser","Bubble Buddy","Dying for Pie","Imitation Krabs","Wormy","Patty Hype","Grandma's Kisses","Squidville", "Prehibernation Week "Life of Crime "Christmas Who?",
  "Survival of the Idiots",
  "Dumped",
  "No Free Rides",
  "I'm Your Biggest Fanatic",
  "Mermaid Man and Barnacle Boy III",
  "Squirrel Jokes",
  "Pressure",
  "The Smoking Peanut",
  "Shanghaied",
  "Gary Takes a Bath",
  "Welcome to the Chum Bucket",
  "Frankendoodle",
  "The Secret Box",
  "Band Geeks",
  "Graveyard Shift",
  "Krusty Love",
  "Procrastination",
  "I'm with Stupid",
  "Sailor Mouth",
  "Artist Unknown",
  "Jellyfish Hunter",
  "The Fry Cook Games",
  "Squid on Strike",
  "Sandy, SpongeBob, and the Worm"
];
